### PR TITLE
Specs views reverted

### PR DESCRIPTION
**Pull request by hiromataba**
In this PR we did the following :point_down: 
- Use Capybara to write integration tests for each view in your project.

- Login page:

   - I can see the username and password inputs and the "Submit" button.
   - When I click the submit button without filling in the username and the password, I get a detailed error.
   - When I click the submit button after filling in the username and the password with incorrect data, I get a detailed error.
   - When I click the submit button after filling in the username and the password with correct data, I am redirected to the root page.
- User index page:

   - I can see the username of all other users.
   - I can see the profile picture for each user.
   - I can see the number of posts each user has written.
   - When I click on a user, I am redirected to that user's show page.
- user show page:

   - I can see the user's profile picture.
   - I can see the user's username.
   - I can see the number of posts the user has written.
   - I can see the user's bio.
   - I can see the user's first 3 posts.
   - I can see a button that lets me view all of a user's posts.
   - When I click a user's post, it redirects me to that post's show page.
   - When I click to see all posts, it redirects me to the user's post's index page.
- User post index page:

   - I can see the user's profile picture.
   - I can see the user's username.
   - I can see the number of posts the user has written.
   - I can see a post's title.
   - I can see some of the post's body.
   - I can see the first comments on a post.
   - I can see how many comments a post has.
   - I can see how many likes a post has.
   - I can see a section for pagination if there are more posts than fit on the view.
   - When I click on a post, it redirects me to that post's show page.
- Post show page:

   - I can see the post's title.
   - I can see who wrote the post.
   - I can see how many comments it has.
   - I can see how many likes it has.
   - I can see the post body.
   - I can see the username of each commenter.
   - I can see the comment each commentor left.

### CODE REVIEW

**Comment by hiromataba** [comment]
I am sorry i accidentally merged the previous branch with the required changes that is why I created this one :pray:

**Review by oxenprogrammer — CHANGES_REQUESTED** [review]
Hi @hiromataba, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] When I run the login integration test in isolation, I get the below error. Since it's a UI test, you should consider using `visit` as well to demonstrate how a user would fill in that form.
I am not sure whether this was something pointed out by the previous reviewer since you haven't attached a link to it.
integration-test-fail

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hiromataba** [comment]
- I think this should be optional since it was not mentioned by the first reviewer and by the way my tests are running 
- Here is the Screenshot :
image

**Comment by oxenprogrammer** [comment]
@hiromataba Thank you for letting me know. The unit tests all pass except for the login UI tests in isolation. Since it wasn't pointed out by the previous Code Reviewer, I will update my review to optional. 
- [ ] It will still be great to look at it and consider correcting it in future.

**Review by oxenprogrammer — APPROVED** [review]
Hi @hiromataba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hiromataba** [comment]
> @hiromataba Thank you for letting me know. The unit tests all pass except for the login UI tests in isolation. Since it wasn't pointed out by the previous Code Reviewer, I will update my review to optional.
> 
> * [ ]  It will still be great to look at it and consider correcting it in future.

- Yeah thank you for the comment ,i am sorry that  I forgot to add the link to the last review since i created another branch because i accidentally merged the one that had the required changes, I am glad the reviewer paid attention to that :pray:

**Pull request merged**
